// Mocks generated by Mockito 5.4.4 from annotations
// in expermed_test/test/app/ui/views/medical_examinations/medical_examination.view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:expermed_test/app/domain/entities/count_services_day.dart'
    as _i5;
import 'package:expermed_test/app/domain/entities/medical_examination.dart'
    as _i4;
import 'package:expermed_test/app/domain/repositories/medical_examination_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MedicalExaminationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicalExaminationRepository extends _i1.Mock
    implements _i2.MedicalExaminationRepository {
  MockMedicalExaminationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MedicalExaminationEntity>> getCalendarServiceEntities(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarServiceEntities,
          [date],
        ),
        returnValue: _i3.Future<List<_i4.MedicalExaminationEntity>>.value(
            <_i4.MedicalExaminationEntity>[]),
      ) as _i3.Future<List<_i4.MedicalExaminationEntity>>);

  @override
  _i3.Future<List<_i5.CountServicesDayEntity>> getMonthCountOfServices(
          int? month) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthCountOfServices,
          [month],
        ),
        returnValue: _i3.Future<List<_i5.CountServicesDayEntity>>.value(
            <_i5.CountServicesDayEntity>[]),
      ) as _i3.Future<List<_i5.CountServicesDayEntity>>);
}
